### ISSUE TITLE
override generator gerando arquivo desnecessário

### ISSUE THREAD

**Issue by ppires** [rarolabs/templus_models#20]
Usei o generator override (`rails g rarocrud:override Cliente new`), e ele gerou 3 arquivos de view:
- _form.html.erb
- _new.html.erb
- new.html.erb

O `_new.html.erb` não é usado, e não precisa ser gerado.

**Comment by diegoqlima** [comment]
Bug referente a outro projeto `http://git.rarolabs.com.br/rarolabs/raro_generator`

**Comment by ppires** [comment]
Issue foi migrada para o raro_generator no gitlab.
