### ISSUE TITLE
Eager loading das associações dos cruds

### ISSUE THREAD

**Issue by ppires** [rarolabs/templus_models#26]
Instalei a gem [bullet](https://github.com/flyerhzm/bullet) no excellence, e percebi que as associações dos models nunca são buscadas junto com o registro. A sugestão é fazer os `includes()` necessários nas associações que serão mostradas na tela. Por exemplo, no index de `Cliente` do excellence são mostradas 3 colunas que são associações (`Nivel`, `TipoAdministracao` e `PlanoSoftware`), e esse foi o warning da bullet:
```
user: pedropires
GET http://localhost:3000/crud/cliente
USE eager loading detected
  Cliente => [:niveis]
  Add to your finder: :includes => [:niveis]
Call stack
  /Users/pedropires/Projects/excellence/app/controllers/application_controller.rb:96:in `set_current_usuario'


user: pedropires
GET http://localhost:3000/crud/cliente
USE eager loading detected
  Cliente => [:tipo_administracao]
  Add to your finder: :includes => [:tipo_administracao]
Call stack
  /Users/pedropires/Projects/excellence/app/controllers/application_controller.rb:96:in `set_current_usuario'


user: pedropires
GET http://localhost:3000/crud/cliente
USE eager loading detected
  Cliente => [:plano_software]
  Add to your finder: :includes => [:plano_software]
Call stack
  /Users/pedropires/Projects/excellence/app/controllers/application_controller.rb:96:in `set_current_usuario'
```

Para a index, da pra implementar pegando os campos que foram declarados com `campo_tabela` e que são associações, e dando um `includes()` neles. 
Pro show teria que pegar os campos declarados com `campo_visualizacao` e que forem associações.
Pro edit teria que dar um include em todas as associações.

**Comment by JuarezLustosa** [comment]
👏  O Ganho de performance é considerável também

**Comment by adimircolen** [comment]
Um exemplo seria, 
adicionar no model_crud o `includes`, para adicionar os modelos de user e rating na query da index.
```
includes :user, :rating

campo_tabela :email, label: "simple_form.shared.email", sort_field: :user_email
```
