### ISSUE TITLE
Relacionamento many to many

### ISSUE THREAD

**Issue by vanessasoutoc** [rarolabs/templus_models#5]
Olá, tenho um cliente que possui essa gem no seu sistema e preciso gerar um relacionamento many to many, entretanto estou com dificuldade! Se alguém puder auxiliar!

Desde já obrigado!

**Comment by leonardoherbert** [comment]
Bom dia Vanessa,

Poderia explicar melhor como é esse relacionamento e o que você está precisando? 

Segue um exemplo que utiliza `has_and_belongs_to_many`
Ex: 
```ruby
class Regioes
   has_and_belongs_to_many :cidades
end

class RegiaoCrud
  campo_formulario :cidades, label: "Cidades", label_method: :estado_cidade
end
```

`label_method` o RaroCrud irá usar esse método como label no lugar do `to_s`.
Se quiser utilizar algum HTML no `select` você pode inserir dentro do `input_html` como no `simple_form`, ex: `input_html: {class: "chosen", data: {placeholder: "Cidades"}}`

**Comment by vanessasoutoc** [comment]
Olá @leonardoherbert já deu certo! 
Muito obrigado pela resposta! 
Muito bom a api de você!

**Comment by diegoqlima** [comment]
Resolvido
